export interface Product {
  id: string
  title: string
  price: number
  image: string
  collection: string
  subcategory?: string
  isNew?: boolean
  salePrice?: number
}

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Blazer Structured Preto',
    price: 4980,
    image: '/products/blazer-structured-preto.png',
    collection: 'PEÇAS ESSENCIAIS',
  },
  {
    id: '2',
    title: 'T-Shirt Oversized',
    price: 2480,
    image: '/products/tshirt-oversized.png',
    collection: 'PRIMAVERA',
    isNew: true,
  },
  {
    id: '3',
    title: 'Calça Slim Fit',
    price: 3320,
    image: '/products/calca-slim-fit.png',
    collection: 'PEÇAS ESSENCIAIS',
    salePrice: 2660,
  },
  {
    id: '4',
    title: 'Jaqueta Biker Deluxe',
    price: 9980,
    image: '/products/jaqueta-biker-deluxe.png',
    collection: 'MAPUTO',
  },
  {
    id: '5',
    title: 'Calções Utility Vintage',
    price: 2320,
    image: '/products/calcoes-utility-vintage.png',
    collection: 'PRIMAVERA',
    isNew: true,
  },
  {
    id: '6',
    title: 'Casaco Longline',
    price: 7480,
    image: '/products/casaco-longline.png',
    collection: 'MAPUTO',
  },
  {
    id: '7',
    title: 'Ténis Retro Edição Limitada',
    price: 5820,
    image: '/products/tenis-retro-edicao-limitada.png',
    collection: 'EDIÇÃO LIMITADA',
  },
  {
    id: '8',
    title: 'Acessórios Signature Ouro',
    price: 3320,
    image: '/products/acessorios-signature-ouro.png',
    collection: 'ACESSÓRIOS',
    salePrice: 2660,
  },
  {
    id: '9',
    title: 'Nike Air Max Runner',
    price: 4500,
    image: '/products/calcados/nike-air-max-runner.png',
    collection: 'CALÇADOS',
    subcategory: 'ESPORTIVAS',
    isNew: true,
  },
  {
    id: '10',
    title: 'Adidas Ultraboost Street',
    price: 5200,
    image: '/products/calcados/adidas-ultraboost-street.png',
    collection: 'CALÇADOS',
    subcategory: 'ESPORTIVAS',
    isNew: true,
  },
  {
    id: '11',
    title: 'New Balance 574 Classic',
    price: 3800,
    image: '/products/calcados/new-balance-574-classic.png',
    collection: 'CALÇADOS',
    subcategory: 'ESPORTIVAS',
  },
  {
    id: '12',
    title: 'Balenciaga Track Elegance',
    price: 9800,
    image: '/products/calcados/balenciaga-track-elegance.png',
    collection: 'CALÇADOS',
    subcategory: 'FORMAIS',
  },
  {
    id: '13',
    title: 'Balenciaga Speed Trainer',
    price: 9500,
    image: '/products/calcados/balenciaga-speed-trainer.png',
    collection: 'CALÇADOS',
    subcategory: 'FORMAIS',
  },
  {
    id: '14',
    title: 'Clarks Oxford Clássico',
    price: 6200,
    image: '/products/calcados/clarks-oxford-classico.png',
    collection: 'CALÇADOS',
    subcategory: 'FORMAIS',
  },
  {
    id: '15',
    title: 'Clarks Derby Couro',
    price: 5800,
    image: '/products/calcados/clarks-derby-couro.png',
    collection: 'CALÇADOS',
    subcategory: 'FORMAIS',
  },
  {
    id: '16',
    title: 'Nike Air Force 1 Classic',
    price: 5600,
    image: '/products/calcados/nike-air-force-1-classic.png',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
  },
  {
    id: '17',
    title: 'Adidas Stan Smith Couro',
    price: 4200,
    image: '/products/calcados/adidas-stan-smith-couro.png',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
  },
  {
    id: '18',
    title: 'New Balance 990',
    price: 6900,
    image: '/products/calcados/new-balance-990.png',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
  },
  {
    id: '19',
    title: 'Timberland Boot Clássica',
    price: 7500,
    image: '/products/calcados/timberland-boot-classica.png',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
  },
  {
    id: '20',
    title: 'Timberland Boot Couro',
    price: 8900,
    image: '/products/calcados/timberland-boot-couro.png',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
  },
]
