export interface ProductVariant {
  color: string
  images: string[]
}

export interface Product {
  id: string
  title: string
  /** Em MT. Ignorado quando `priceOnRequest` é verdadeiro. */
  price: number
  /** Preço sob consulta: não mostra valor nem permite comprar pela sacola; o cliente pede o preço no WhatsApp. */
  priceOnRequest?: boolean
  image: string
  collection: string
  subcategory?: string
  isNew?: boolean
  salePrice?: number
  sizes?: string[]
  colors?: string[]
  /** Cores com fotos próprias; quando existe, substitui `colors` e a foto muda com a cor. */
  variants?: ProductVariant[]
  /** Galeria de fotos quando não há variantes por cor. */
  images?: string[]
  /** Fotos extra na galeria que não pertencem a nenhuma cor (ex.: todas as cores juntas). */
  extraImages?: string[]
}

export const SNEAKER_COLORS = ['Preto', 'Branco', 'Cinzento', 'Azul', 'Vermelho']
export const FORMAL_COLORS = ['Preto', 'Castanho']

const CLOTHING_SIZES = ['S', 'M', 'L', 'XL']
export const SHOE_SIZES = ['38', '39', '40', '41', '42', '43', '44', '45']
const NB530_SIZES = ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45']

// Tamanhos por defeito consoante a categoria (calçado, vestuário, acessórios sem tamanho).
// Um produto pode definir `sizes` ou `colors` próprios para sobrepor.
export function getProductSizes(product: Product): string[] {
  if (product.sizes) return product.sizes
  if (product.collection === 'CALÇADOS') return SHOE_SIZES
  if (product.collection === 'ACESSÓRIOS') return []
  return CLOTHING_SIZES
}

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Blazer Structured Preto',
    price: 4980,
    image: '/products/blazer-structured-preto.png',
    collection: 'PEÇAS ESSENCIAIS',
  },
  {
    id: '2',
    title: 'T-Shirt Oversized',
    price: 2480,
    image: '/products/tshirt-oversized.png',
    collection: 'PRIMAVERA',
    isNew: true,
  },
  {
    id: '3',
    title: 'Calça Slim Fit',
    price: 3320,
    image: '/products/calca-slim-fit.png',
    collection: 'PEÇAS ESSENCIAIS',
    salePrice: 2660,
  },
  {
    id: '4',
    title: 'Jaqueta Biker Deluxe',
    price: 9980,
    image: '/products/jaqueta-biker-deluxe.png',
    collection: 'MAPUTO',
  },
  {
    id: '5',
    title: 'Calções Utility Vintage',
    price: 2320,
    image: '/products/calcoes-utility-vintage.png',
    collection: 'PRIMAVERA',
    isNew: true,
  },
  {
    id: '6',
    title: 'Casaco Longline',
    price: 7480,
    image: '/products/casaco-longline.png',
    collection: 'MAPUTO',
  },
  {
    id: '7',
    title: 'Ténis Retro Edição Limitada',
    price: 5820,
    image: '/products/tenis-retro-edicao-limitada.jpg',
    collection: 'EDIÇÃO LIMITADA',
    sizes: SHOE_SIZES,
    colors: SNEAKER_COLORS,
  },
  {
    id: '8',
    title: 'Acessórios Signature Ouro',
    price: 3320,
    image: '/products/acessorios-signature-ouro.png',
    collection: 'ACESSÓRIOS',
    salePrice: 2660,
  },
  {
    id: '9',
    title: 'Nike Air Max Runner',
    price: 4500,
    image: '/products/calcados/nike-air-max-runner.png',
    collection: 'CALÇADOS',
    subcategory: 'ESPORTIVAS',
    isNew: true,
    colors: SNEAKER_COLORS,
  },
  {
    id: '10',
    title: 'Adidas Ultraboost Street',
    price: 5200,
    image: '/products/calcados/adidas-ultraboost-street.png',
    collection: 'CALÇADOS',
    subcategory: 'ESPORTIVAS',
    isNew: true,
    colors: SNEAKER_COLORS,
  },
  {
    id: '11',
    title: 'New Balance 574 Classic',
    price: 3800,
    image: '/products/calcados/new-balance-574-classic.png',
    collection: 'CALÇADOS',
    subcategory: 'ESPORTIVAS',
    colors: SNEAKER_COLORS,
  },
  {
    id: '12',
    title: 'Balenciaga Track Elegance',
    price: 9800,
    image: '/products/calcados/balenciaga-track-elegance.png',
    collection: 'CALÇADOS',
    subcategory: 'FORMAIS',
    colors: SNEAKER_COLORS,
  },
  {
    id: '13',
    title: 'Balenciaga Speed Trainer',
    price: 9500,
    image: '/products/calcados/balenciaga-speed-trainer.png',
    collection: 'CALÇADOS',
    subcategory: 'FORMAIS',
    colors: SNEAKER_COLORS,
  },
  {
    id: '14',
    title: 'Clarks Oxford Clássico',
    price: 6200,
    image: '/products/calcados/clarks-oxford-classico.png',
    collection: 'CALÇADOS',
    subcategory: 'FORMAIS',
    colors: FORMAL_COLORS,
  },
  {
    id: '15',
    title: 'Clarks Derby Couro',
    price: 5800,
    image: '/products/calcados/clarks-derby-couro.png',
    collection: 'CALÇADOS',
    subcategory: 'FORMAIS',
    colors: FORMAL_COLORS,
  },
  {
    id: '16',
    title: 'Nike Air Force 1 Classic',
    price: 5600,
    image: '/products/calcados/nike-air-force-1-classic.png',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    colors: SNEAKER_COLORS,
  },
  {
    id: '17',
    title: 'Adidas Stan Smith Couro',
    price: 4200,
    image: '/products/calcados/adidas-stan-smith-couro.png',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    colors: SNEAKER_COLORS,
  },
  {
    id: '18',
    title: 'New Balance 990',
    price: 6900,
    image: '/products/calcados/new-balance-990.png',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    colors: SNEAKER_COLORS,
  },
  {
    id: '19',
    title: 'Timberland Boot Clássica',
    price: 7500,
    image: '/products/calcados/timberland-boot-classica.png',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    colors: FORMAL_COLORS,
  },
  {
    id: '20',
    title: 'Timberland Boot Couro',
    price: 8900,
    image: '/products/calcados/timberland-boot-couro.png',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    colors: FORMAL_COLORS,
  },
  {
    id: '21',
    title: 'New Balance 530',
    price: 3000,
    image: '/products/calcados/new-balance-530-azul-1.jpg',
    collection: 'CALÇADOS',
    subcategory: 'ESPORTIVAS',
    isNew: true,
    sizes: NB530_SIZES,
    variants: [
      {
        color: 'Branco e Azul',
        images: [
          '/products/calcados/new-balance-530-azul-1.jpg',
          '/products/calcados/new-balance-530-azul-2.jpg',
          '/products/calcados/new-balance-530-azul-3.jpg',
          '/products/calcados/new-balance-530-azul-4.jpg',
        ],
      },
      {
        color: 'Branco e Preto',
        images: [
          '/products/calcados/new-balance-530-preto-1.jpg',
          '/products/calcados/new-balance-530-preto-2.jpg',
          '/products/calcados/new-balance-530-preto-3.jpg',
        ],
      },
    ],
  },
  {
    id: '22',
    title: 'Calções Jeans',
    price: 1700,
    image: '/products/calcoes-jeans-1.jpg',
    collection: 'PRIMAVERA',
    isNew: true,
    images: Array.from({ length: 7 }, (_, i) => `/products/calcoes-jeans-${i + 1}.jpg`),
  },
  {
    id: '23',
    title: 'Air Force 1 AIR-FLEA',
    price: 3500,
    image: '/products/calcados/air-force-1-air-flea-preto-1.jpg',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    isNew: true,
    sizes: ['39', '40', '41', '42', '43', '44'],
    variants: [
      {
        color: 'Preto',
        images: [
          '/products/calcados/air-force-1-air-flea-preto-1.jpg',
          '/products/calcados/air-force-1-air-flea-preto-2.jpg',
        ],
      },
      {
        color: 'Branco',
        images: [
          '/products/calcados/air-force-1-air-flea-branco-1.jpg',
          '/products/calcados/air-force-1-air-flea-branco-2.jpg',
        ],
      },
    ],
  },
  {
    id: '24',
    title: 'Conjunto Feminino',
    price: 3500,
    image: '/products/conjunto-feminino-branco-1.jpg',
    collection: 'PRIMAVERA',
    isNew: true,
    variants: [
      {
        color: 'Branco',
        images: [
          '/products/conjunto-feminino-branco-1.jpg',
          '/products/conjunto-feminino-branco-2.jpg',
        ],
      },
      {
        color: 'Rosa',
        images: [
          '/products/conjunto-feminino-rosa-1.jpg',
          '/products/conjunto-feminino-rosa-2.jpg',
        ],
      },
      {
        color: 'Preto',
        images: [
          '/products/conjunto-feminino-preto-1.jpg',
          '/products/conjunto-feminino-preto-2.jpg',
        ],
      },
      {
        color: 'Bege',
        images: [
          '/products/conjunto-feminino-bege-1.jpg',
          '/products/conjunto-feminino-bege-2.jpg',
        ],
      },
    ],
  },
  {
    id: '25',
    title: 'Camisa Polo Lacoste',
    price: 1770,
    image: '/products/polo-lacoste-1.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    colors: ['Branco', 'Preto', 'Azul Marinho', 'Verde', 'Vermelho'],
    images: Array.from({ length: 6 }, (_, i) => `/products/polo-lacoste-${i + 1}.jpg`),
  },
  {
    id: '26',
    title: 'Conjunto Oversized',
    price: 2800,
    image: '/products/conjunto-oversized-preto.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    variants: [
      { color: 'Preto', images: ['/products/conjunto-oversized-preto.jpg'] },
      { color: 'Cinzento Escuro', images: ['/products/conjunto-oversized-cinzento-escuro.jpg'] },
      { color: 'Azul Céu', images: ['/products/conjunto-oversized-azul-ceu.jpg'] },
      { color: 'Verde Sálvia', images: ['/products/conjunto-oversized-verde-salvia.jpg'] },
      { color: 'Verde Escuro', images: ['/products/conjunto-oversized-verde-escuro.jpg'] },
      { color: 'Verde Oliva', images: ['/products/conjunto-oversized-oliva.jpg'] },
      { color: 'Cinzento Claro', images: ['/products/conjunto-oversized-cinzento-claro.jpg'] },
      { color: 'Branco', images: ['/products/conjunto-oversized-branco.jpg'] },
    ],
  },
  {
    id: '27',
    title: 'Camisa Oversized',
    price: 1600,
    image: '/products/camisa-oversized-bege.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    variants: [
      { color: 'Bege', images: ['/products/camisa-oversized-bege.jpg'] },
      { color: 'Branco', images: ['/products/camisa-oversized-branco.jpg'] },
      { color: 'Creme', images: ['/products/camisa-oversized-creme.jpg'] },
      { color: 'Rosa', images: ['/products/camisa-oversized-rosa.jpg'] },
      { color: 'Cinzento Escuro', images: ['/products/camisa-oversized-cinzento-escuro.jpg'] },
      { color: 'Areia', images: ['/products/camisa-oversized-areia.jpg'] },
      { color: 'Verde Menta', images: ['/products/camisa-oversized-verde-menta.jpg'] },
    ],
    extraImages: ['/products/camisa-oversized-todas-as-cores.jpg'],
  },
  {
    id: '28',
    title: 'Conjunto NOCTA',
    price: 2950,
    image: '/products/conjunto-nocta-preto-1.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    variants: [
      { color: 'Preto', images: ['/products/conjunto-nocta-preto-1.jpg'] },
      { color: 'Branco', images: ['/products/conjunto-nocta-branco-1.jpg'] },
      { color: 'Bege', images: ['/products/conjunto-nocta-bege-1.jpg'] },
    ],
  },
  {
    id: '29',
    title: 'Camiseta NOCTA',
    price: 1450,
    image: '/products/camiseta-nocta-preto.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    variants: [
      { color: 'Preto', images: ['/products/camiseta-nocta-preto.jpg'] },
      { color: 'Bege', images: ['/products/camiseta-nocta-bege.jpg'] },
      { color: 'Cinzento', images: ['/products/camiseta-nocta-cinzento.jpg'] },
    ],
    extraImages: ['/products/camiseta-nocta-todas-as-cores.jpg'],
  },
  {
    id: '30',
    title: 'T-shirt Supreme',
    price: 1500,
    image: '/products/tshirt-supreme-1.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    images: [1, 2, 3, 5].map((n) => `/products/tshirt-supreme-${n}.jpg`),
  },
  {
    id: '31',
    title: 'T-shirt Brasil',
    price: 1500,
    image: '/products/tshirt-brasil-1.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    colors: ['Amarelo', 'Branco', 'Azul Marinho'],
    images: [1, 3, 4, 5, 6].map((n) => `/products/tshirt-brasil-${n}.jpg`),
  },
  {
    id: '32',
    title: 'Calções Gallery Dept',
    price: 1550,
    image: '/products/calcoes-gallery-dept-1.jpg',
    collection: 'PRIMAVERA',
    isNew: true,
    sizes: ['30', '32', '34', '36', '38'],
    images: Array.from({ length: 5 }, (_, i) => `/products/calcoes-gallery-dept-${i + 1}.jpg`),
  },
  {
    id: '33',
    title: 'Jordan Retro 4',
    price: 2450,
    image: '/products/calcados/jordan-retro-4-branco-vermelho-1.jpg',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    isNew: true,
    variants: [
      { color: 'Branco e Vermelho', images: ['/products/calcados/jordan-retro-4-branco-vermelho-1.jpg'] },
      { color: 'Preto e Roxo', images: ['/products/calcados/jordan-retro-4-preto-roxo-1.jpg'] },
      { color: 'Verde Escuro', images: ['/products/calcados/jordan-retro-4-verde-escuro-1.jpg', '/products/calcados/jordan-retro-4-verde-escuro-2.jpg'] },
      { color: 'Branco e Azul Royal', images: ['/products/calcados/jordan-retro-4-branco-azul-royal-1.jpg'] },
      { color: 'Roxo', images: ['/products/calcados/jordan-retro-4-roxo-1.jpg'] },
      { color: 'Cinzento e Azul', images: ['/products/calcados/jordan-retro-4-cinzento-azul-1.jpg'] },
      { color: 'Branco e Verde', images: ['/products/calcados/jordan-retro-4-branco-verde-1.jpg'] },
      { color: 'Cinzento e Menta', images: ['/products/calcados/jordan-retro-4-cinzento-menta-1.jpg'] },
      { color: 'Branco Multicor', images: ['/products/calcados/jordan-retro-4-branco-multicor-1.jpg'] },
      { color: 'Branco e Azul Marinho', images: ['/products/calcados/jordan-retro-4-branco-azul-marinho-1.jpg'] },
      { color: 'Vermelho e Azul', images: ['/products/calcados/jordan-retro-4-vermelho-azul-1.jpg'] },
      { color: 'Preto e Vermelho', images: ['/products/calcados/jordan-retro-4-preto-vermelho-1.jpg'] },
      { color: 'Branco e Bordô', images: ['/products/calcados/jordan-retro-4-branco-bordo-1.jpg'] },
      { color: 'Azul Claro', images: ['/products/calcados/jordan-retro-4-azul-claro-1.jpg'] },
      { color: 'Creme e Verde', images: ['/products/calcados/jordan-retro-4-creme-verde-1.jpg'] },
    ],
    extraImages: ['/products/calcados/jordan-retro-4-todas.jpg'],
  },
  {
    id: '34',
    title: 'Calções Nike Classic',
    price: 1350,
    image: '/products/calcoes-nike-classic-vermelho.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    sizes: ['M', 'L', 'XL', 'XXL', 'XXXL'],
    variants: [
      { color: 'Vermelho', images: ['/products/calcoes-nike-classic-vermelho.jpg'] },
      { color: 'Azul', images: ['/products/calcoes-nike-classic-azul.jpg'] },
      { color: 'Preto', images: ['/products/calcoes-nike-classic-preto.jpg'] },
      { color: 'Branco', images: ['/products/calcoes-nike-classic-branco.jpg'] },
    ],
    extraImages: ['/products/calcoes-nike-classic-todas-as-cores.jpg'],
  },
  {
    id: '35',
    title: 'Calções Nike NOCTA',
    price: 1450,
    image: '/products/calcoes-nike-nocta-preto.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    variants: [
      { color: 'Vermelho', images: ['/products/calcoes-nike-nocta-vermelho.jpg'] },
      { color: 'Preto', images: ['/products/calcoes-nike-nocta-preto.jpg'] },
      { color: 'Roxo', images: ['/products/calcoes-nike-nocta-roxo.jpg'] },
      { color: 'Azul Marinho', images: ['/products/calcoes-nike-nocta-azul-marinho.jpg'] },
      { color: 'Coral', images: ['/products/calcoes-nike-nocta-coral.jpg'] },
      { color: 'Cinzento', images: ['/products/calcoes-nike-nocta-cinzento.jpg'] },
    ],
    extraImages: ['/products/calcoes-nike-nocta-todas-as-cores.jpg'],
  },
  {
    id: '36',
    title: 'Air Jordan 1 Rasa',
    price: 2499,
    image: '/products/calcados/air-jordan-1-rasa-preto-branco.jpg',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    isNew: true,
    sizes: ['37', '38', '39', '40', '41', '42', '43', '44', '45'],
    variants: [
      { color: 'Preto e Branco', images: ['/products/calcados/air-jordan-1-rasa-preto-branco.jpg'] },
      { color: 'Bordô e Preto', images: ['/products/calcados/air-jordan-1-rasa-borbo-preto.jpg'] },
      { color: 'Preto Total', images: ['/products/calcados/air-jordan-1-rasa-preto-total.jpg'] },
      { color: 'Preto Camurça', images: ['/products/calcados/air-jordan-1-rasa-preto-camurca.jpg'] },
      { color: 'Azul Marinho', images: ['/products/calcados/air-jordan-1-rasa-azul-marinho.jpg'] },
      { color: 'Preto e Cinzento', images: ['/products/calcados/air-jordan-1-rasa-preto-cinzento.jpg'] },
      { color: 'Branco, Preto e Vermelho', images: ['/products/calcados/air-jordan-1-rasa-branco-preto-vermelho.jpg'] },
      { color: 'Branco', images: ['/products/calcados/air-jordan-1-rasa-branco.jpg'] },
      { color: 'Cinzento e Branco', images: ['/products/calcados/air-jordan-1-rasa-cinzento-branco.jpg'] },
      { color: 'Preto, Vermelho e Creme', images: ['/products/calcados/air-jordan-1-rasa-preto-vermelho-creme.jpg'] },
      { color: 'Preto, Branco e Castanho', images: ['/products/calcados/air-jordan-1-rasa-preto-branco-castanho.jpg'] },
      { color: 'Vermelho e Preto', images: ['/products/calcados/air-jordan-1-rasa-vermelho-preto.jpg'] },
      { color: 'Azul Marinho e Cinzento', images: ['/products/calcados/air-jordan-1-rasa-azul-marinho-cinzento-1.jpg', '/products/calcados/air-jordan-1-rasa-azul-marinho-cinzento-2.jpg', '/products/calcados/air-jordan-1-rasa-azul-marinho-cinzento-3.jpg'] },
      { color: 'Cinzento Escuro e Branco', images: ['/products/calcados/air-jordan-1-rasa-cinzento-escuro-branco-1.jpg', '/products/calcados/air-jordan-1-rasa-cinzento-escuro-branco-2.jpg'] },
      { color: 'Verde Militar', images: ['/products/calcados/air-jordan-1-rasa-verde-militar-1.jpg', '/products/calcados/air-jordan-1-rasa-verde-militar-2.jpg'] },
      { color: 'PSG Preto e Vermelho', images: ['/products/calcados/air-jordan-1-rasa-psg-preto-vermelho-1.jpg', '/products/calcados/air-jordan-1-rasa-psg-preto-vermelho-2.jpg', '/products/calcados/air-jordan-1-rasa-psg-preto-vermelho-3.jpg'] },
      { color: 'Preto Elefante Amarelo', images: ['/products/calcados/air-jordan-1-rasa-preto-elefante-amarelo-1.jpg', '/products/calcados/air-jordan-1-rasa-preto-elefante-amarelo-2.jpg', '/products/calcados/air-jordan-1-rasa-preto-elefante-amarelo-3.jpg'] },
      { color: 'Verde Oliva e Branco', images: ['/products/calcados/air-jordan-1-rasa-verde-oliva-branco-1.jpg', '/products/calcados/air-jordan-1-rasa-verde-oliva-branco-2.jpg'] },
    ],
  },
  {
    id: '37',
    title: 'Crocs Classic',
    price: 1350,
    image: '/products/calcados/crocs-classic-preto.jpg',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    isNew: true,
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
    variants: [
      { color: 'Creme', images: ['/products/calcados/crocs-classic-creme.jpg'] },
      { color: 'Branco', images: ['/products/calcados/crocs-classic-branco.jpg'] },
      { color: 'Cinzento', images: ['/products/calcados/crocs-classic-cinzento.jpg'] },
      { color: 'Bege', images: ['/products/calcados/crocs-classic-bege.jpg'] },
      { color: 'Azul Marinho', images: ['/products/calcados/crocs-classic-azul-marinho.jpg'] },
      { color: 'Rosa', images: ['/products/calcados/crocs-classic-rosa.jpg'] },
      { color: 'Preto', images: ['/products/calcados/crocs-classic-preto.jpg'] },
    ],
  },
  {
    id: '38',
    title: 'Chinelos Tommy Hilfiger',
    price: 1500,
    image: '/products/calcados/chinelos-tommy-faixa-preto-1.jpg',
    collection: 'CALÇADOS',
    subcategory: 'CHINELOS',
    isNew: true,
    variants: [
      { color: 'Medalhão Castanho', images: ['/products/calcados/chinelos-tommy-medalhao-castanho-1.jpg'] },
      { color: 'Medalhão Preto', images: ['/products/calcados/chinelos-tommy-medalhao-preto-1.jpg'] },
      { color: 'Medalhão Cinzento', images: ['/products/calcados/chinelos-tommy-medalhao-cinzento-1.jpg'] },
      { color: 'Medalhão Azul Marinho', images: ['/products/calcados/chinelos-tommy-medalhao-azul-marinho-1.jpg'] },
      { color: 'Relevo Azul Marinho', images: ['/products/calcados/chinelos-tommy-relevo-azul-marinho-1.jpg'] },
      { color: 'Relevo Cinzento', images: ['/products/calcados/chinelos-tommy-relevo-cinzento-1.jpg'] },
      { color: 'Relevo Castanho', images: ['/products/calcados/chinelos-tommy-relevo-castanho-1.jpg'] },
      { color: 'Monograma Preto', images: ['/products/calcados/chinelos-tommy-monograma-preto-1.jpg'] },
      { color: 'Monograma Azul Marinho', images: ['/products/calcados/chinelos-tommy-monograma-azul-marinho-1.jpg'] },
      { color: 'TH Vermelho', images: ['/products/calcados/chinelos-tommy-th-vermelho-1.jpg'] },
      { color: 'Clássico Preto e Azul Marinho', images: ['/products/calcados/chinelos-tommy-classico-preto-azul-1.jpg'] },
      { color: 'Bandeira Preto', images: ['/products/calcados/chinelos-tommy-bandeira-preto-1.jpg', '/products/calcados/chinelos-tommy-bandeira-preto-2.jpg'] },
      { color: 'Bandeira Azul Marinho', images: ['/products/calcados/chinelos-tommy-bandeira-azul-marinho-1.jpg'] },
      { color: 'Diagonal Azul', images: ['/products/calcados/chinelos-tommy-diagonal-azul-1.jpg'] },
      { color: 'Diagonal Preto', images: ['/products/calcados/chinelos-tommy-diagonal-preto-1.jpg'] },
      { color: 'Faixa Azul Marinho', images: ['/products/calcados/chinelos-tommy-faixa-azul-marinho-1.jpg'] },
      { color: 'Faixa Preto', images: ['/products/calcados/chinelos-tommy-faixa-preto-1.jpg'] },
    ],
  },
  {
    id: '39',
    title: 'Calções Diesel',
    price: 1450,
    image: '/products/calcoes-diesel-azul-escuro.jpg',
    collection: 'PRIMAVERA',
    isNew: true,
    sizes: ['32', '34', '36'],
    variants: [
      { color: 'Azul Escuro', images: ['/products/calcoes-diesel-azul-escuro.jpg'] },
      { color: 'Azul Médio', images: ['/products/calcoes-diesel-azul-medio.jpg'] },
      { color: 'Azul Claro', images: ['/products/calcoes-diesel-azul-claro.jpg'] },
      { color: 'Azul Lavado', images: ['/products/calcoes-diesel-azul-lavado.jpg'] },
    ],
  },
  {
    id: '40',
    title: 'Conjunto Linho Loro Piana',
    price: 0,
    priceOnRequest: true,
    image: '/products/conjunto-linho-loro-piana-branco-1.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    variants: [
      {
        color: 'Branco',
        images: ['/products/conjunto-linho-loro-piana-branco-1.jpg', '/products/conjunto-linho-loro-piana-branco-2.jpg', '/products/conjunto-linho-loro-piana-branco-3.jpg', '/products/conjunto-linho-loro-piana-branco-4.jpg'],
      },
      {
        color: 'Preto',
        images: ['/products/conjunto-linho-loro-piana-preto-1.jpg', '/products/conjunto-linho-loro-piana-preto-2.jpg'],
      },
      {
        color: 'Cinzento',
        images: ['/products/conjunto-linho-loro-piana-cinzento-1.jpg', '/products/conjunto-linho-loro-piana-cinzento-2.jpg', '/products/conjunto-linho-loro-piana-cinzento-3.jpg'],
      },
      {
        color: 'Verde Caqui',
        images: ['/products/conjunto-linho-loro-piana-verde-caqui-1.jpg'],
      },
    ],
  },
  {
    id: '41',
    title: 'Camisa de Linho às Riscas',
    price: 0,
    priceOnRequest: true,
    image: '/products/camisa-linho-riscas-azul.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    variants: [
      { color: 'Azul', images: ['/products/camisa-linho-riscas-azul.jpg'] },
      { color: 'Rosa', images: ['/products/camisa-linho-riscas-rosa.jpg'] },
      { color: 'Azul Claro', images: ['/products/camisa-linho-riscas-azul-claro.jpg'] },
      { color: 'Vermelho', images: ['/products/camisa-linho-riscas-vermelho.jpg'] },
      { color: 'Verde', images: ['/products/camisa-linho-riscas-verde.jpg'] },
    ],
  },
  {
    id: '42',
    title: 'Bonés',
    price: 1199,
    image: '/products/bones-modelo-01.jpg',
    collection: 'ACESSÓRIOS',
    isNew: true,
    variants: [
      { color: 'MA Preto e Branco', images: ['/products/bones-modelo-01.jpg'] },
      { color: 'NY Creme e Castanho', images: ['/products/bones-modelo-02.jpg'] },
      { color: 'Cinzento Desgastado', images: ['/products/bones-modelo-03.jpg'] },
      { color: 'NY Desgastado Azul e Preto', images: ['/products/bones-modelo-04.jpg'] },
      { color: 'NY Desgastado Cinzento e Bege', images: ['/products/bones-modelo-05.jpg'] },
      { color: 'MA Rosa', images: ['/products/bones-modelo-06.jpg'] },
      { color: 'IH Preto e Branco', images: ['/products/bones-modelo-07.jpg'] },
      { color: 'CH Castanho', images: ['/products/bones-modelo-08.jpg'] },
      { color: 'Trucker Vermelho e Branco', images: ['/products/bones-modelo-09.jpg'] },
      { color: 'AMI Preto', images: ['/products/bones-modelo-10.jpg'] },
      { color: 'MA Creme e Castanho', images: ['/products/bones-modelo-11.jpg'] },
      { color: 'BBC Preto e Dourado', images: ['/products/bones-modelo-12.jpg'] },
      { color: 'Preto Cruz Branca', images: ['/products/bones-modelo-13.jpg'] },
      { color: 'Godspeed Preto Couro', images: ['/products/bones-modelo-14.jpg'] },
      { color: 'Cruzes Coloridas Preto', images: ['/products/bones-modelo-15.jpg'] },
      { color: 'Nylon Azul Marinho e Bege', images: ['/products/bones-modelo-16.jpg'] },
      { color: 'Preto Logo Laranja e Azul', images: ['/products/bones-modelo-17.jpg'] },
      { color: 'SD Creme e Castanho', images: ['/products/bones-modelo-18.jpg'] },
      { color: 'Trucker Cruz Preto e Branco', images: ['/products/bones-modelo-19.jpg'] },
      { color: 'Trucker Verde Néon', images: ['/products/bones-modelo-20.jpg'] },
      { color: 'Trucker Preto e Azul Laranja', images: ['/products/bones-modelo-21.jpg'] },
      { color: 'Estrelas Preto', images: ['/products/bones-modelo-22.jpg'] },
      { color: 'Trucker Preto Letras Laranja', images: ['/products/bones-modelo-23.jpg'] },
      { color: 'CH Roxo', images: ['/products/bones-modelo-24.jpg'] },
      { color: 'MA Creme e Azul', images: ['/products/bones-modelo-25.jpg'] },
      { color: 'Trucker Graffiti Preto e Branco', images: ['/products/bones-modelo-26.jpg'] },
      { color: 'Trucker Graffiti Castanho', images: ['/products/bones-modelo-27.jpg'] },
      { color: 'IH Castanho e Branco', images: ['/products/bones-modelo-28.jpg'] },
      { color: 'CH Rosa', images: ['/products/bones-modelo-29.jpg'] },
      { color: 'Trucker Preto Cinzento', images: ['/products/bones-modelo-30.jpg'] },
      { color: 'Trucker Rosa', images: ['/products/bones-modelo-31.jpg'] },
    ],
    extraImages: ['/products/bones-todas-1.jpg', '/products/bones-todas-2.jpg'],
  },
  {
    id: '43',
    title: 'Mochila Goyard',
    price: 2649,
    image: '/products/mochila-vermelho-1.jpg',
    collection: 'ACESSÓRIOS',
    isNew: true,
    variants: [
      {
        color: 'Vermelho',
        images: ['/products/mochila-vermelho-1.jpg', '/products/mochila-vermelho-2.jpg', '/products/mochila-vermelho-3.jpg', '/products/mochila-vermelho-4.jpg'],
      },
      {
        color: 'Verde',
        images: ['/products/mochila-verde-1.jpg', '/products/mochila-verde-2.jpg', '/products/mochila-verde-3.jpg', '/products/mochila-verde-4.jpg', '/products/mochila-verde-5.jpg', '/products/mochila-verde-6.jpg'],
      },
      {
        color: 'Preto',
        images: ['/products/mochila-preto-1.jpg', '/products/mochila-preto-2.jpg', '/products/mochila-preto-3.jpg', '/products/mochila-preto-4.jpg'],
      },
      {
        color: 'Cinzento',
        images: ['/products/mochila-cinzento-1.jpg', '/products/mochila-cinzento-2.jpg', '/products/mochila-cinzento-3.jpg'],
      },
    ],
  },
  {
    id: '44',
    title: 'Birkenstock Boston',
    price: 2850,
    image: '/products/calcados/birkenstock-boston-preto.jpg',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    isNew: true,
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
    variants: [
      { color: 'Areia', images: ['/products/calcados/birkenstock-boston-areia.jpg'] },
      { color: 'Cinzento Claro', images: ['/products/calcados/birkenstock-boston-cinzento-claro.jpg'] },
      { color: 'Cinzento', images: ['/products/calcados/birkenstock-boston-cinzento.jpg'] },
      { color: 'Castanho', images: ['/products/calcados/birkenstock-boston-castanho.jpg'] },
      { color: 'Preto', images: ['/products/calcados/birkenstock-boston-preto.jpg'] },
      { color: 'Rosa', images: ['/products/calcados/birkenstock-boston-rosa.jpg'] },
      { color: 'Verde Caqui', images: ['/products/calcados/birkenstock-boston-verde-caqui.jpg'] },
    ],
    extraImages: ['/products/calcados/birkenstock-boston-todas-1.jpg', '/products/calcados/birkenstock-boston-todas-2.jpg'],
  },
  {
    id: '45',
    title: 'Camiseta de Malha',
    price: 1450,
    image: '/products/camiseta-malha-1.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Bordô', 'Creme', 'Preto', 'Cinzento'],
    images: ['/products/camiseta-malha-1.jpg', '/products/camiseta-malha-2.jpg'],
  },
  {
    id: '46',
    title: 'Calções Nike Jordan',
    price: 2550,
    image: '/products/calcoes-nike-jordan-1.jpg',
    collection: 'PRIMAVERA',
    isNew: true,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Azul Claro', 'Cinzento', 'Preto', 'Vermelho', 'Branco'],
    images: Array.from({ length: 5 }, (_, i) => `/products/calcoes-nike-jordan-${i + 1}.jpg`),
  },
  {
    id: '47',
    title: 'Fato Cruzado',
    price: 7500,
    image: '/products/fato-cruzado-preto-1.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    variants: [
      { color: 'Preto', images: ['/products/fato-cruzado-preto-1.jpg', '/products/fato-cruzado-preto-2.jpg'] },
      { color: 'Bege', images: ['/products/fato-cruzado-bege-1.jpg'] },
      { color: 'Camel', images: ['/products/fato-cruzado-camel-1.jpg'] },
      { color: 'Azul Marinho', images: ['/products/fato-cruzado-azul-marinho-1.jpg', '/products/fato-cruzado-azul-marinho-2.jpg'] },
      { color: 'Cinzento', images: ['/products/fato-cruzado-cinzento-1.jpg'] },
      { color: 'Castanho', images: ['/products/fato-cruzado-castanho-1.jpg'] },
    ],
  },
  {
    id: '48',
    title: 'Ténis Numeris',
    price: 5999,
    image: '/products/calcados/tenis-numeris-1.jpg',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    isNew: true,
    sizes: ['40', '41', '42', '43', '44', '45'],
    images: Array.from({ length: 3 }, (_, i) => `/products/calcados/tenis-numeris-${i + 1}.jpg`),
  },
  {
    id: '49',
    title: 'Adidas Superstar',
    price: 3499,
    image: '/products/calcados/adidas-superstar-branco-azul-marinho-1.jpg',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    isNew: true,
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    variants: [
      { color: 'Branco e Azul Marinho', images: ['/products/calcados/adidas-superstar-branco-azul-marinho-1.jpg', '/products/calcados/adidas-superstar-branco-azul-marinho-2.jpg', '/products/calcados/adidas-superstar-branco-azul-marinho-3.jpg'] },
      { color: 'Cinzento', images: ['/products/calcados/adidas-superstar-cinzento-1.jpg', '/products/calcados/adidas-superstar-cinzento-2.jpg'] },
    ],
  },
  {
    id: '50',
    title: 'Ténis Lacoste',
    price: 3499,
    image: '/products/calcados/tenis-lacoste-preto.jpg',
    collection: 'CALÇADOS',
    subcategory: 'MAIS',
    isNew: true,
    sizes: ['40', '41', '42', '43', '44', '45'],
    variants: [
      { color: 'Cinzento Escuro', images: ['/products/calcados/tenis-lacoste-cinzento-escuro.jpg'] },
      { color: 'Preto', images: ['/products/calcados/tenis-lacoste-preto.jpg'] },
    ],
  },
  {
    id: '51',
    title: 'New Balance 327',
    price: 2850,
    image: '/products/calcados/new-balance-327-branco-cinzento-verde.jpg',
    collection: 'CALÇADOS',
    subcategory: 'ESPORTIVAS',
    isNew: true,
    sizes: ['37', '38', '39', '40', '41', '42', '43', '44'],
    variants: [
      { color: 'Branco, Cinzento e Verde', images: ['/products/calcados/new-balance-327-branco-cinzento-verde.jpg'] },
      { color: 'Azul Petróleo', images: ['/products/calcados/new-balance-327-azul-petroleo.jpg'] },
    ],
  },
  {
    id: '52',
    title: 'New Balance 480',
    price: 3500,
    image: '/products/calcados/new-balance-480-preto-branco.jpg',
    collection: 'CALÇADOS',
    subcategory: 'ESPORTIVAS',
    isNew: true,
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
    variants: [
      { color: 'Branco e Verde', images: ['/products/calcados/new-balance-480-branco-verde.jpg'] },
      { color: 'Preto e Branco', images: ['/products/calcados/new-balance-480-preto-branco.jpg'] },
      { color: 'Cinzento e Branco', images: ['/products/calcados/new-balance-480-cinzento-branco.jpg'] },
      { color: 'Preto', images: ['/products/calcados/new-balance-480-preto.jpg'] },
      { color: 'Cinzento Escuro e Bege', images: ['/products/calcados/new-balance-480-cinzento-escuro-bege.jpg'] },
    ],
  },
  {
    id: '53',
    title: 'Colete BOSS',
    price: 3850,
    image: '/products/colete-boss-1.jpg',
    collection: 'PEÇAS ESSENCIAIS',
    isNew: true,
    images: Array.from({ length: 3 }, (_, i) => `/products/colete-boss-${i + 1}.jpg`),
  },
]

export function getProductById(id: string) {
  return FEATURED_PRODUCTS.find((p) => p.id === id)
}
